# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rate', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meds',
            name='rate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
