# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170719_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='meds',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
