# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_meds_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
