# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-24 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170724_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meds',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='meds',
            name='rate',
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
