# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-24 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20170724_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='meds',
        ),
    ]
