# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-24 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meds',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
