# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-24 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_auto_20170724_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='meds',
            field=models.ManyToManyField(default='', related_name='ordered_meds', to='products.meds'),
        ),
    ]
