# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-24 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_cart_meds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meds',
            name='quantity',
        ),
    ]
