# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_cart_meds'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('rate', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
