# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-26 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='meds',
        ),
    ]
