# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_remove_cart_meds'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(default='', null=True, related_name='item', to='products.cart_item'),
        ),
        migrations.AddField(
            model_name='cart_item',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
