# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_auto_20170726_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
    ]
