# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20170727_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(default='', null=True, related_name='item', to='products.cart_item'),
        ),
    ]
