# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20170727_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_item',
            field=models.ManyToManyField(default='', related_name='item', to='products.cart_item'),
        ),
    ]
