# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-27 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0042_auto_20170727_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_item',
            name='orderer',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to=settings.AUTH_USER_MODEL),
        ),
    ]
